// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebGame.Server.Data;

#nullable disable

namespace WebGame.Server.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20251220200046_fix")]
    partial class fix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("WebGame.Server.Models.Building", b =>
                {
                    b.Property<int>("BuildingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InitialCost")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTownHall")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ResourceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("BuildingId");

                    b.HasIndex("ResourceId");

                    b.ToTable("Buldings");

                    b.HasData(
                        new
                        {
                            BuildingId = 1,
                            Description = "Popis radnice",
                            Height = 7,
                            InitialCost = 0,
                            IsTownHall = true,
                            Name = "Radnice",
                            ResourceId = 2,
                            Width = 10
                        },
                        new
                        {
                            BuildingId = 2,
                            Description = "Popis domu",
                            Height = 6,
                            InitialCost = 90,
                            IsTownHall = false,
                            Name = "Domek",
                            ResourceId = 2,
                            Width = 4
                        },
                        new
                        {
                            BuildingId = 3,
                            Description = "Popis kostelu",
                            Height = 9,
                            InitialCost = 100,
                            IsTownHall = false,
                            Name = "Kostel",
                            ResourceId = 2,
                            Width = 6
                        },
                        new
                        {
                            BuildingId = 4,
                            Description = "Popis střelnice",
                            Height = 7,
                            InitialCost = 110,
                            IsTownHall = false,
                            Name = "Střelnice",
                            ResourceId = 3,
                            Width = 6
                        },
                        new
                        {
                            BuildingId = 5,
                            Description = "Popis zbrojírny",
                            Height = 7,
                            InitialCost = 120,
                            IsTownHall = false,
                            Name = "Zbrojírna",
                            ResourceId = 3,
                            Width = 6
                        },
                        new
                        {
                            BuildingId = 6,
                            Description = "Popis věže",
                            Height = 7,
                            InitialCost = 130,
                            IsTownHall = false,
                            Name = "Věž",
                            ResourceId = 3,
                            Width = 4
                        });
                });

            modelBuilder.Entity("WebGame.Server.Models.BuildingLevel", b =>
                {
                    b.Property<int>("BuildingId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GainIntervalSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ResourceGain")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UpgradeCost")
                        .HasColumnType("INTEGER");

                    b.HasKey("BuildingId", "Level");

                    b.ToTable("BuildingLevels");

                    b.HasData(
                        new
                        {
                            BuildingId = 1,
                            Level = 1,
                            GainIntervalSeconds = 30,
                            ResourceGain = 10,
                            UpgradeCost = 100
                        },
                        new
                        {
                            BuildingId = 1,
                            Level = 2,
                            GainIntervalSeconds = 30,
                            ResourceGain = 20,
                            UpgradeCost = 200
                        },
                        new
                        {
                            BuildingId = 1,
                            Level = 3,
                            GainIntervalSeconds = 30,
                            ResourceGain = 30,
                            UpgradeCost = 300
                        },
                        new
                        {
                            BuildingId = 1,
                            Level = 4,
                            GainIntervalSeconds = 30,
                            ResourceGain = 40,
                            UpgradeCost = 400
                        },
                        new
                        {
                            BuildingId = 1,
                            Level = 5,
                            GainIntervalSeconds = 30,
                            ResourceGain = 50,
                            UpgradeCost = 500
                        },
                        new
                        {
                            BuildingId = 1,
                            Level = 6,
                            GainIntervalSeconds = 30,
                            ResourceGain = 60,
                            UpgradeCost = 600
                        },
                        new
                        {
                            BuildingId = 1,
                            Level = 7,
                            GainIntervalSeconds = 30,
                            ResourceGain = 70,
                            UpgradeCost = 700
                        },
                        new
                        {
                            BuildingId = 1,
                            Level = 8,
                            GainIntervalSeconds = 30,
                            ResourceGain = 80,
                            UpgradeCost = 800
                        },
                        new
                        {
                            BuildingId = 1,
                            Level = 9,
                            GainIntervalSeconds = 30,
                            ResourceGain = 90,
                            UpgradeCost = 900
                        },
                        new
                        {
                            BuildingId = 1,
                            Level = 10,
                            GainIntervalSeconds = 30,
                            ResourceGain = 100,
                            UpgradeCost = 1000
                        },
                        new
                        {
                            BuildingId = 2,
                            Level = 1,
                            GainIntervalSeconds = 30,
                            ResourceGain = 10,
                            UpgradeCost = 100
                        },
                        new
                        {
                            BuildingId = 2,
                            Level = 2,
                            GainIntervalSeconds = 30,
                            ResourceGain = 20,
                            UpgradeCost = 200
                        },
                        new
                        {
                            BuildingId = 2,
                            Level = 3,
                            GainIntervalSeconds = 30,
                            ResourceGain = 30,
                            UpgradeCost = 300
                        },
                        new
                        {
                            BuildingId = 2,
                            Level = 4,
                            GainIntervalSeconds = 30,
                            ResourceGain = 40,
                            UpgradeCost = 400
                        },
                        new
                        {
                            BuildingId = 2,
                            Level = 5,
                            GainIntervalSeconds = 30,
                            ResourceGain = 50,
                            UpgradeCost = 500
                        },
                        new
                        {
                            BuildingId = 2,
                            Level = 6,
                            GainIntervalSeconds = 30,
                            ResourceGain = 60,
                            UpgradeCost = 600
                        },
                        new
                        {
                            BuildingId = 2,
                            Level = 7,
                            GainIntervalSeconds = 30,
                            ResourceGain = 70,
                            UpgradeCost = 700
                        },
                        new
                        {
                            BuildingId = 2,
                            Level = 8,
                            GainIntervalSeconds = 30,
                            ResourceGain = 80,
                            UpgradeCost = 800
                        },
                        new
                        {
                            BuildingId = 2,
                            Level = 9,
                            GainIntervalSeconds = 30,
                            ResourceGain = 90,
                            UpgradeCost = 900
                        },
                        new
                        {
                            BuildingId = 2,
                            Level = 10,
                            GainIntervalSeconds = 30,
                            ResourceGain = 100,
                            UpgradeCost = 1000
                        },
                        new
                        {
                            BuildingId = 3,
                            Level = 1,
                            GainIntervalSeconds = 30,
                            ResourceGain = 10,
                            UpgradeCost = 100
                        },
                        new
                        {
                            BuildingId = 3,
                            Level = 2,
                            GainIntervalSeconds = 30,
                            ResourceGain = 20,
                            UpgradeCost = 200
                        },
                        new
                        {
                            BuildingId = 3,
                            Level = 3,
                            GainIntervalSeconds = 30,
                            ResourceGain = 30,
                            UpgradeCost = 300
                        },
                        new
                        {
                            BuildingId = 3,
                            Level = 4,
                            GainIntervalSeconds = 30,
                            ResourceGain = 40,
                            UpgradeCost = 400
                        },
                        new
                        {
                            BuildingId = 3,
                            Level = 5,
                            GainIntervalSeconds = 30,
                            ResourceGain = 50,
                            UpgradeCost = 500
                        },
                        new
                        {
                            BuildingId = 3,
                            Level = 6,
                            GainIntervalSeconds = 30,
                            ResourceGain = 60,
                            UpgradeCost = 600
                        },
                        new
                        {
                            BuildingId = 3,
                            Level = 7,
                            GainIntervalSeconds = 30,
                            ResourceGain = 70,
                            UpgradeCost = 700
                        },
                        new
                        {
                            BuildingId = 3,
                            Level = 8,
                            GainIntervalSeconds = 30,
                            ResourceGain = 80,
                            UpgradeCost = 800
                        },
                        new
                        {
                            BuildingId = 3,
                            Level = 9,
                            GainIntervalSeconds = 30,
                            ResourceGain = 90,
                            UpgradeCost = 900
                        },
                        new
                        {
                            BuildingId = 3,
                            Level = 10,
                            GainIntervalSeconds = 30,
                            ResourceGain = 100,
                            UpgradeCost = 1000
                        },
                        new
                        {
                            BuildingId = 4,
                            Level = 1,
                            GainIntervalSeconds = 30,
                            ResourceGain = 10,
                            UpgradeCost = 100
                        },
                        new
                        {
                            BuildingId = 4,
                            Level = 2,
                            GainIntervalSeconds = 30,
                            ResourceGain = 20,
                            UpgradeCost = 200
                        },
                        new
                        {
                            BuildingId = 4,
                            Level = 3,
                            GainIntervalSeconds = 30,
                            ResourceGain = 30,
                            UpgradeCost = 300
                        },
                        new
                        {
                            BuildingId = 4,
                            Level = 4,
                            GainIntervalSeconds = 30,
                            ResourceGain = 40,
                            UpgradeCost = 400
                        },
                        new
                        {
                            BuildingId = 4,
                            Level = 5,
                            GainIntervalSeconds = 30,
                            ResourceGain = 50,
                            UpgradeCost = 500
                        },
                        new
                        {
                            BuildingId = 4,
                            Level = 6,
                            GainIntervalSeconds = 30,
                            ResourceGain = 60,
                            UpgradeCost = 600
                        },
                        new
                        {
                            BuildingId = 4,
                            Level = 7,
                            GainIntervalSeconds = 30,
                            ResourceGain = 70,
                            UpgradeCost = 700
                        },
                        new
                        {
                            BuildingId = 4,
                            Level = 8,
                            GainIntervalSeconds = 30,
                            ResourceGain = 80,
                            UpgradeCost = 800
                        },
                        new
                        {
                            BuildingId = 4,
                            Level = 9,
                            GainIntervalSeconds = 30,
                            ResourceGain = 90,
                            UpgradeCost = 900
                        },
                        new
                        {
                            BuildingId = 4,
                            Level = 10,
                            GainIntervalSeconds = 30,
                            ResourceGain = 100,
                            UpgradeCost = 1000
                        },
                        new
                        {
                            BuildingId = 5,
                            Level = 1,
                            GainIntervalSeconds = 30,
                            ResourceGain = 10,
                            UpgradeCost = 100
                        },
                        new
                        {
                            BuildingId = 5,
                            Level = 2,
                            GainIntervalSeconds = 30,
                            ResourceGain = 20,
                            UpgradeCost = 200
                        },
                        new
                        {
                            BuildingId = 5,
                            Level = 3,
                            GainIntervalSeconds = 30,
                            ResourceGain = 30,
                            UpgradeCost = 300
                        },
                        new
                        {
                            BuildingId = 5,
                            Level = 4,
                            GainIntervalSeconds = 30,
                            ResourceGain = 40,
                            UpgradeCost = 400
                        },
                        new
                        {
                            BuildingId = 5,
                            Level = 5,
                            GainIntervalSeconds = 30,
                            ResourceGain = 50,
                            UpgradeCost = 500
                        },
                        new
                        {
                            BuildingId = 5,
                            Level = 6,
                            GainIntervalSeconds = 30,
                            ResourceGain = 60,
                            UpgradeCost = 600
                        },
                        new
                        {
                            BuildingId = 5,
                            Level = 7,
                            GainIntervalSeconds = 30,
                            ResourceGain = 70,
                            UpgradeCost = 700
                        },
                        new
                        {
                            BuildingId = 5,
                            Level = 8,
                            GainIntervalSeconds = 30,
                            ResourceGain = 80,
                            UpgradeCost = 800
                        },
                        new
                        {
                            BuildingId = 5,
                            Level = 9,
                            GainIntervalSeconds = 30,
                            ResourceGain = 90,
                            UpgradeCost = 900
                        },
                        new
                        {
                            BuildingId = 5,
                            Level = 10,
                            GainIntervalSeconds = 30,
                            ResourceGain = 100,
                            UpgradeCost = 1000
                        },
                        new
                        {
                            BuildingId = 6,
                            Level = 1,
                            GainIntervalSeconds = 30,
                            ResourceGain = 10,
                            UpgradeCost = 100
                        },
                        new
                        {
                            BuildingId = 6,
                            Level = 2,
                            GainIntervalSeconds = 30,
                            ResourceGain = 20,
                            UpgradeCost = 200
                        },
                        new
                        {
                            BuildingId = 6,
                            Level = 3,
                            GainIntervalSeconds = 30,
                            ResourceGain = 30,
                            UpgradeCost = 300
                        },
                        new
                        {
                            BuildingId = 6,
                            Level = 4,
                            GainIntervalSeconds = 30,
                            ResourceGain = 40,
                            UpgradeCost = 400
                        },
                        new
                        {
                            BuildingId = 6,
                            Level = 5,
                            GainIntervalSeconds = 30,
                            ResourceGain = 50,
                            UpgradeCost = 500
                        },
                        new
                        {
                            BuildingId = 6,
                            Level = 6,
                            GainIntervalSeconds = 30,
                            ResourceGain = 60,
                            UpgradeCost = 600
                        },
                        new
                        {
                            BuildingId = 6,
                            Level = 7,
                            GainIntervalSeconds = 30,
                            ResourceGain = 70,
                            UpgradeCost = 700
                        },
                        new
                        {
                            BuildingId = 6,
                            Level = 8,
                            GainIntervalSeconds = 30,
                            ResourceGain = 80,
                            UpgradeCost = 800
                        },
                        new
                        {
                            BuildingId = 6,
                            Level = 9,
                            GainIntervalSeconds = 30,
                            ResourceGain = 90,
                            UpgradeCost = 900
                        },
                        new
                        {
                            BuildingId = 6,
                            Level = 10,
                            GainIntervalSeconds = 30,
                            ResourceGain = 100,
                            UpgradeCost = 1000
                        });
                });

            modelBuilder.Entity("WebGame.Server.Models.Map", b =>
                {
                    b.Property<int>("MapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MapId");

                    b.ToTable("Maps");

                    b.HasData(
                        new
                        {
                            MapId = 1,
                            Title = "Default ground layer"
                        },
                        new
                        {
                            MapId = 2,
                            Title = "Default building layer"
                        });
                });

            modelBuilder.Entity("WebGame.Server.Models.MapBuilding", b =>
                {
                    b.Property<int>("BuildingId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MapId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TopLeftX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TopLeftY")
                        .HasColumnType("INTEGER");

                    b.HasKey("BuildingId", "MapId");

                    b.HasIndex("MapId");

                    b.ToTable("MapBuildings");

                    b.HasData(
                        new
                        {
                            BuildingId = 1,
                            MapId = 2,
                            TopLeftX = 5,
                            TopLeftY = 5
                        });
                });

            modelBuilder.Entity("WebGame.Server.Models.MapTile", b =>
                {
                    b.Property<int>("TileId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MapId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("X")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Y")
                        .HasColumnType("INTEGER");

                    b.HasKey("TileId", "MapId");

                    b.HasIndex("MapId");

                    b.ToTable("MapTiles");
                });

            modelBuilder.Entity("WebGame.Server.Models.Resource", b =>
                {
                    b.Property<int>("ResourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ResourceId");

                    b.ToTable("Resources");

                    b.HasData(
                        new
                        {
                            ResourceId = 1,
                            Description = "Popis ovce",
                            Name = "Ovce"
                        },
                        new
                        {
                            ResourceId = 2,
                            Description = "Popis populace",
                            Name = "Populace"
                        },
                        new
                        {
                            ResourceId = 3,
                            Description = "Popis vojska",
                            Name = "Vojsko"
                        });
                });

            modelBuilder.Entity("WebGame.Server.Models.Tile", b =>
                {
                    b.Property<int>("TileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPlacable")
                        .HasColumnType("INTEGER");

                    b.HasKey("TileId");

                    b.ToTable("Tiles");

                    b.HasData(
                        new
                        {
                            TileId = 1,
                            IsPlacable = true
                        },
                        new
                        {
                            TileId = 2,
                            IsPlacable = true
                        },
                        new
                        {
                            TileId = 3,
                            IsPlacable = true
                        },
                        new
                        {
                            TileId = 5,
                            IsPlacable = true
                        },
                        new
                        {
                            TileId = 6,
                            IsPlacable = true
                        },
                        new
                        {
                            TileId = 7,
                            IsPlacable = true
                        },
                        new
                        {
                            TileId = 8,
                            IsPlacable = true
                        },
                        new
                        {
                            TileId = 9,
                            IsPlacable = true
                        },
                        new
                        {
                            TileId = 10,
                            IsPlacable = true
                        },
                        new
                        {
                            TileId = 11,
                            IsPlacable = true
                        },
                        new
                        {
                            TileId = 12,
                            IsPlacable = true
                        },
                        new
                        {
                            TileId = 14,
                            IsPlacable = true
                        },
                        new
                        {
                            TileId = 15,
                            IsPlacable = true
                        },
                        new
                        {
                            TileId = 16,
                            IsPlacable = true
                        },
                        new
                        {
                            TileId = 17,
                            IsPlacable = true
                        },
                        new
                        {
                            TileId = 18,
                            IsPlacable = true
                        },
                        new
                        {
                            TileId = 19,
                            IsPlacable = true
                        },
                        new
                        {
                            TileId = 20,
                            IsPlacable = true
                        },
                        new
                        {
                            TileId = 21,
                            IsPlacable = true
                        },
                        new
                        {
                            TileId = 23,
                            IsPlacable = true
                        },
                        new
                        {
                            TileId = 24,
                            IsPlacable = true
                        },
                        new
                        {
                            TileId = 25,
                            IsPlacable = true
                        },
                        new
                        {
                            TileId = 26,
                            IsPlacable = true
                        },
                        new
                        {
                            TileId = 27,
                            IsPlacable = true
                        },
                        new
                        {
                            TileId = 28,
                            IsPlacable = true
                        },
                        new
                        {
                            TileId = 29,
                            IsPlacable = true
                        },
                        new
                        {
                            TileId = 30,
                            IsPlacable = true
                        },
                        new
                        {
                            TileId = 32,
                            IsPlacable = false
                        },
                        new
                        {
                            TileId = 33,
                            IsPlacable = false
                        },
                        new
                        {
                            TileId = 34,
                            IsPlacable = false
                        },
                        new
                        {
                            TileId = 35,
                            IsPlacable = false
                        },
                        new
                        {
                            TileId = 36,
                            IsPlacable = false
                        },
                        new
                        {
                            TileId = 39,
                            IsPlacable = false
                        },
                        new
                        {
                            TileId = 41,
                            IsPlacable = true
                        },
                        new
                        {
                            TileId = 42,
                            IsPlacable = true
                        },
                        new
                        {
                            TileId = 43,
                            IsPlacable = true
                        },
                        new
                        {
                            TileId = 44,
                            IsPlacable = true
                        },
                        new
                        {
                            TileId = 45,
                            IsPlacable = false
                        },
                        new
                        {
                            TileId = 48,
                            IsPlacable = false
                        },
                        new
                        {
                            TileId = 50,
                            IsPlacable = false
                        },
                        new
                        {
                            TileId = 51,
                            IsPlacable = false
                        },
                        new
                        {
                            TileId = 52,
                            IsPlacable = false
                        },
                        new
                        {
                            TileId = 53,
                            IsPlacable = false
                        },
                        new
                        {
                            TileId = 54,
                            IsPlacable = true
                        },
                        new
                        {
                            TileId = 55,
                            IsPlacable = true
                        },
                        new
                        {
                            TileId = 56,
                            IsPlacable = true
                        },
                        new
                        {
                            TileId = 57,
                            IsPlacable = true
                        },
                        new
                        {
                            TileId = 59,
                            IsPlacable = true
                        },
                        new
                        {
                            TileId = 60,
                            IsPlacable = true
                        },
                        new
                        {
                            TileId = 61,
                            IsPlacable = true
                        },
                        new
                        {
                            TileId = 62,
                            IsPlacable = true
                        },
                        new
                        {
                            TileId = 63,
                            IsPlacable = true
                        },
                        new
                        {
                            TileId = 64,
                            IsPlacable = true
                        },
                        new
                        {
                            TileId = 65,
                            IsPlacable = true
                        },
                        new
                        {
                            TileId = 66,
                            IsPlacable = true
                        },
                        new
                        {
                            TileId = 68,
                            IsPlacable = true
                        },
                        new
                        {
                            TileId = 69,
                            IsPlacable = true
                        },
                        new
                        {
                            TileId = 70,
                            IsPlacable = true
                        },
                        new
                        {
                            TileId = 71,
                            IsPlacable = true
                        },
                        new
                        {
                            TileId = 72,
                            IsPlacable = true
                        },
                        new
                        {
                            TileId = 73,
                            IsPlacable = true
                        },
                        new
                        {
                            TileId = 74,
                            IsPlacable = true
                        },
                        new
                        {
                            TileId = 75,
                            IsPlacable = true
                        },
                        new
                        {
                            TileId = 77,
                            IsPlacable = true
                        },
                        new
                        {
                            TileId = 78,
                            IsPlacable = true
                        },
                        new
                        {
                            TileId = 79,
                            IsPlacable = true
                        },
                        new
                        {
                            TileId = 80,
                            IsPlacable = true
                        },
                        new
                        {
                            TileId = 81,
                            IsPlacable = true
                        },
                        new
                        {
                            TileId = 82,
                            IsPlacable = true
                        },
                        new
                        {
                            TileId = 83,
                            IsPlacable = true
                        },
                        new
                        {
                            TileId = 84,
                            IsPlacable = true
                        },
                        new
                        {
                            TileId = 86,
                            IsPlacable = false
                        },
                        new
                        {
                            TileId = 87,
                            IsPlacable = false
                        },
                        new
                        {
                            TileId = 88,
                            IsPlacable = false
                        },
                        new
                        {
                            TileId = 89,
                            IsPlacable = false
                        },
                        new
                        {
                            TileId = 90,
                            IsPlacable = false
                        },
                        new
                        {
                            TileId = 93,
                            IsPlacable = false
                        },
                        new
                        {
                            TileId = 95,
                            IsPlacable = true
                        },
                        new
                        {
                            TileId = 96,
                            IsPlacable = true
                        },
                        new
                        {
                            TileId = 97,
                            IsPlacable = true
                        },
                        new
                        {
                            TileId = 98,
                            IsPlacable = true
                        },
                        new
                        {
                            TileId = 99,
                            IsPlacable = false
                        },
                        new
                        {
                            TileId = 102,
                            IsPlacable = false
                        },
                        new
                        {
                            TileId = 104,
                            IsPlacable = false
                        },
                        new
                        {
                            TileId = 105,
                            IsPlacable = false
                        },
                        new
                        {
                            TileId = 106,
                            IsPlacable = false
                        },
                        new
                        {
                            TileId = 107,
                            IsPlacable = false
                        });
                });

            modelBuilder.Entity("WebGame.Server.Models.Building", b =>
                {
                    b.HasOne("WebGame.Server.Models.Resource", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceId");

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("WebGame.Server.Models.BuildingLevel", b =>
                {
                    b.HasOne("WebGame.Server.Models.Building", null)
                        .WithMany("Levels")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebGame.Server.Models.MapBuilding", b =>
                {
                    b.HasOne("WebGame.Server.Models.Building", "Building")
                        .WithMany()
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebGame.Server.Models.Map", null)
                        .WithMany("Buildings")
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");
                });

            modelBuilder.Entity("WebGame.Server.Models.MapTile", b =>
                {
                    b.HasOne("WebGame.Server.Models.Map", null)
                        .WithMany("Tiles")
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebGame.Server.Models.Tile", "Tile")
                        .WithMany()
                        .HasForeignKey("TileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tile");
                });

            modelBuilder.Entity("WebGame.Server.Models.Building", b =>
                {
                    b.Navigation("Levels");
                });

            modelBuilder.Entity("WebGame.Server.Models.Map", b =>
                {
                    b.Navigation("Buildings");

                    b.Navigation("Tiles");
                });
#pragma warning restore 612, 618
        }
    }
}
