// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebGame.Server.Data;

#nullable disable

namespace WebGame.Server.Migrations
{
    [DbContext(typeof(GameDbContext))]
    partial class GameDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("WebGame.Server.Models.Building", b =>
                {
                    b.Property<int>("BuildingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InitialCost")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTownHall")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ResourceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("BuildingId");

                    b.HasIndex("ResourceId");

                    b.ToTable("Bulding");

                    b.HasData(
                        new
                        {
                            BuildingId = 1,
                            Description = "Popis radnice",
                            Height = 7,
                            InitialCost = 0,
                            IsTownHall = true,
                            Name = "Radnice",
                            ResourceId = 2,
                            Width = 10
                        },
                        new
                        {
                            BuildingId = 2,
                            Description = "Popis domu",
                            Height = 6,
                            InitialCost = 90,
                            IsTownHall = false,
                            Name = "Domek",
                            ResourceId = 2,
                            Width = 4
                        },
                        new
                        {
                            BuildingId = 3,
                            Description = "Popis kostelu",
                            Height = 9,
                            InitialCost = 100,
                            IsTownHall = false,
                            Name = "Kostel",
                            ResourceId = 2,
                            Width = 6
                        },
                        new
                        {
                            BuildingId = 4,
                            Description = "Popis střelnice",
                            Height = 7,
                            InitialCost = 110,
                            IsTownHall = false,
                            Name = "Střelnice",
                            ResourceId = 3,
                            Width = 6
                        },
                        new
                        {
                            BuildingId = 5,
                            Description = "Popis zbrojírny",
                            Height = 7,
                            InitialCost = 120,
                            IsTownHall = false,
                            Name = "Zbrojírna",
                            ResourceId = 3,
                            Width = 6
                        },
                        new
                        {
                            BuildingId = 6,
                            Description = "Popis věže",
                            Height = 7,
                            InitialCost = 130,
                            IsTownHall = false,
                            Name = "Věž",
                            ResourceId = 3,
                            Width = 4
                        });
                });

            modelBuilder.Entity("WebGame.Server.Models.BuildingLevel", b =>
                {
                    b.Property<int>("BuildingId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GainIntervalSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ResourceGain")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UpgradeCost")
                        .HasColumnType("INTEGER");

                    b.HasKey("BuildingId", "Level");

                    b.ToTable("BuildingLevel");
                });

            modelBuilder.Entity("WebGame.Server.Models.Resource", b =>
                {
                    b.Property<int>("ResourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ResourceId");

                    b.ToTable("Resource");

                    b.HasData(
                        new
                        {
                            ResourceId = 1,
                            Description = "Popis ovce",
                            Name = "Ovce"
                        },
                        new
                        {
                            ResourceId = 2,
                            Description = "Popis populace",
                            Name = "Populace"
                        },
                        new
                        {
                            ResourceId = 3,
                            Description = "Popis vojska",
                            Name = "Vojsko"
                        });
                });

            modelBuilder.Entity("WebGame.Server.Models.Building", b =>
                {
                    b.HasOne("WebGame.Server.Models.Resource", "Resource")
                        .WithMany("Buildings")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("WebGame.Server.Models.BuildingLevel", b =>
                {
                    b.HasOne("WebGame.Server.Models.Building", "Building")
                        .WithMany("Levels")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");
                });

            modelBuilder.Entity("WebGame.Server.Models.Building", b =>
                {
                    b.Navigation("Levels");
                });

            modelBuilder.Entity("WebGame.Server.Models.Resource", b =>
                {
                    b.Navigation("Buildings");
                });
#pragma warning restore 612, 618
        }
    }
}
